steps:
  - label: "Pack"
    command: .buildkite/steps/pack.sh
    key: pack
    artifact_paths: "helloworld-*.tgz"
    plugins:
      - generate-provenance-attestation#v1.1.0:
          artifacts: "helloworld-*.tgz"
          attestation_name: "helloworld-attestation.json"

  - label: "Publish"
    depends_on: "pack"
    plugins:
      - publish-to-packages#v2.2.0:
          artifacts: "helloworld-*.tgz"
          registry: "test-engine-sandbox/hello-world"
          attestations:
            - "helloworld-attestation.json"
